#!/usr/bin/env bash
# lib.sh — the checks the TS toolchain does not already do, defined once.
#
# Each check writes neutral records to stdout, one per line:
#
#     rule<TAB>level<TAB>path<TAB>line<TAB>message
#
# gate.sh renders them for humans, findings.sh renders them as JSONL. Nothing
# in here knows about either format — that is the whole point. Define a check
# once, render it twice.
#
# Sourced, never executed directly.

# ── ai_lint <file...> ────────────────────────────────────────────────────────
# Residue a type-checker cannot see. Three rules, and each one was checked
# against Biome 2.5.13 before being written: a file containing all three
# produces ZERO Biome diagnostics, so none of this double-reports.
#
# Every rule pipeline ends in `|| true`, and that is load-bearing: grep exits 1
# when a rule does not match, which is the normal case. Callers run this under
# `set -euo pipefail` inside a process substitution, so an unguarded non-match
# would kill the subshell and silently skip every later rule and every later
# file. Same for god_files below.
ai_lint() {
  local f
  for f in "$@"; do
    case "$f" in
      node_modules/*|*/node_modules/*|dist/*|*/dist/*|build/*|*/build/*) continue ;;
      *.d.ts|*.min.js|*.gen.ts|*_pb.ts) continue ;;
    esac
    [ -f "$f" ] || continue
    head -5 "$f" 2>/dev/null | grep -qE '^(//|/\*|\s*\*) *(@generated|Code generated|Generated by|prettier-ignore-start)' && continue

    grep -nHE '(TODO|FIXME|XXX)\((claude|ai|bot|gpt|assistant|copilot|codex)\b' "$f" 2>/dev/null \
      | _rec agent-todo error 'agent-tagged TODO — give it a real owner or open an issue' || true
    grep -nHE '//.*\b([Aa]s requested|[Pp]er your request|[Aa]s you (asked|requested|wanted)|[Ii]n response to your request)\b' "$f" 2>/dev/null \
      | _rec ai-self-ref error 'prompt artifact — the comment is talking to the agent' || true
    grep -nHE '//[[:space:]]*(REMOVED|PREVIOUSLY|WAS):[[:space:]]' "$f" 2>/dev/null \
      | _rec diff-relic error 'diff relic — belongs in commit history, not source' || true
  done
}

# _rec <rule> <level> <message>  — turn `path:line:text` on stdin into records.
_rec() {
  local rule="$1" level="$2" msg="$3" line path lineno
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    path="${line%%:*}"; lineno="${line#*:}"; lineno="${lineno%%:*}"
    printf '%s\t%s\t%s\t%s\t%s\n' "$rule" "$level" "$path" "$lineno" "$msg"
  done
}

# ── god_files ────────────────────────────────────────────────────────────────
# The one structural cap Biome has no opinion about. Complexity is NOT here:
# Biome's complexity group owns that, enforced by the lint gate with no second
# tool and no second parse.
god_files() {
  local cap="${CAP_LOC:-500}"
  # `-c core.quotePath=` keeps a non-ASCII path as its own bytes instead of
  # C-quoting it into "cr\303\251ate.ts", which names no file on disk.
  #
  # awk takes the path as everything after the count, not as $2: `wc -l` pads
  # the count and then prints the name verbatim, so a path containing a space
  # reported as $2 is truncated at that space. `xargs` splits a large repo into
  # batches and each batch ends in a `total` line; no source path can be the
  # bare word `total`, so dropping it by name is exact.
  git -c core.quotePath= ls-files -- '*.ts' '*.tsx' '*.js' '*.jsx' '*.mts' '*.cts' 2>/dev/null \
    | grep -vE '(^|/)(node_modules|dist|build|coverage|\.next|out)/|\.d\.ts$|\.min\.js$|\.gen\.ts$' \
    | tr '\n' '\0' | xargs -0 wc -l 2>/dev/null \
    | awk -v cap="$cap" '{
        path = $0; sub(/^[[:space:]]*[0-9]+[[:space:]]+/, "", path)
        if ($1 > cap && path != "total")
          printf "god-file\twarning\t%s\t1\t%d LOC over the %d cap\n", path, $1, cap }' \
    || true
}

# ── staged_ts / tracked_ts ───────────────────────────────────────────────────
# Biome has its own --staged/--changed, and the gate uses those for linting.
# These exist for ai_lint and god_files, which are ours and know nothing of git.
#
# `--relative` is load-bearing and was a real bug. `git ls-files` prints paths
# relative to the CWD, but `git diff --cached --name-only` prints them relative
# to the REPO ROOT. In a repo gated with `dir: web` — which is the layout this
# module exists to serve — that meant staged_ts returned `web/src/x.ts` while
# the gate was standing in `web/`, every `[ -f "$f" ]` in ai_lint failed, and
# the step reported "ai-lint: clean" having read nothing at all. `--relative`
# makes both functions speak the same coordinates.
staged_ts()  { git diff --cached --relative --name-only --diff-filter=ACMR -- '*.ts' '*.tsx' '*.js' '*.jsx' '*.mts' '*.cts' 2>/dev/null; }
tracked_ts() { git ls-files -- '*.ts' '*.tsx' '*.js' '*.jsx' '*.mts' '*.cts' 2>/dev/null; }

# ── ui_lint <file...> ────────────────────────────────────────────────────────
# The two stylesheet rules the fleet's UI guide (docs/UI.md) states and no
# tool checks. Biome lints .css files but has no class-naming rule, and it
# never looks at a Svelte or Vue <style> block at all, so a grep is the only
# thing that sees both repos the same way.
#
#   bem-class     every class selector is block, block__element,
#                 block--modifier or block__element--modifier, or matches
#                 UI_CLASS_ALLOW (default: is-*, has-*, hljs-*, sr-only)
#   raw-color     a hex / rgb() / hsl() literal outside a custom-property
#                 declaration — use a token
#   raw-radius    border-radius with a px/rem literal — use a token
#   raw-duration  transition/animation with a literal duration other than
#                 0s, 0ms or the 0.01ms reduced-motion kill switch — use a token
#
# Only stylesheets: *.css, *.scss, and the <style> blocks of *.svelte / *.vue.
# Class ATTRIBUTES in markup are not selectors and are not read. Warnings, not
# errors: a repo adopting this has an existing stylesheet, and the guide says
# which way to move, not that the move is done.
ui_lint() {
  [ "$#" -gt 0 ] || return 0
  UI_CLASS_ALLOW="${UI_CLASS_ALLOW:-^(is|has|hljs)-|^sr-only$}" python3 - "$@" <<'PY' || true
import os, re, sys

allow = re.compile(os.environ["UI_CLASS_ALLOW"])
bem = re.compile(r"^[a-z][a-z0-9]*(-[a-z0-9]+)*(__[a-z][a-z0-9]*(-[a-z0-9]+)*)?(--[a-z][a-z0-9]*(-[a-z0-9]+)*)?$")
cls = re.compile(r"(?<![\w.-])\.([A-Za-z_][\w-]*)")
color = re.compile(r"#[0-9a-fA-F]{3,8}\b|\b(?:rgba?|hsla?)\(")
radius = re.compile(r"\bborder-(?:\w+-)?radius\s*:[^;{}]*\d(?:px|rem|em)")
duration = re.compile(r"\b(?:transition|animation)(?:-duration)?\s*:[^;{}]*?(?<![\w.])(\d*\.?\d+)(m?s)\b")
custom_prop = re.compile(r"^\s*--[\w-]+\s*:")
style_block = re.compile(r"<style\b[^>]*>(.*?)</style>", re.S)

def rec(rule, level, path, line, msg):
    print(f"{rule}\t{level}\t{path}\t{line}\t{msg}")

def strip_comments(text):
    return re.sub(r"/\*.*?\*/", lambda m: re.sub(r"[^\n]", " ", m.group(0)), text, flags=re.S)

def stylesheets(path):
    """Yield (line_offset, css_text) for every stylesheet region in the file."""
    text = open(path, encoding="utf-8", errors="replace").read()
    if path.endswith((".svelte", ".vue")):
        for m in style_block.finditer(text):
            yield text.count("\n", 0, m.start(1)), m.group(1)
    else:
        yield 0, text

def check(path):
    for offset, css in stylesheets(path):
        css = strip_comments(css)
        # Selectors: everything between a `}`/`;`/`{`/start and the next `{`.
        depth_media = 0
        seen = set()
        for m in re.finditer(r"([^{};]*)\{", css):
            sel = m.group(1)
            if sel.lstrip().startswith("@"):
                continue
            sel = re.sub(r"url\([^)]*\)|\"[^\"]*\"|'[^']*'", "", sel)
            line = offset + css.count("\n", 0, m.start(1)) + 1
            for c in cls.finditer(sel):
                name = c.group(1)
                if name in seen: continue
                seen.add(name)
                if bem.match(name) or allow.search(name): continue
                rec("bem-class", "warning", path, line + sel.count("\n", 0, c.start()),
                    f".{name} is not block, block__element, block--modifier or block__element--modifier")
        for i, raw in enumerate(css.split("\n"), start=offset + 1):
            if custom_prop.match(raw): continue
            if color.search(raw):
                rec("raw-color", "warning", path, i, "color literal — use a token (var(--…))")
            if radius.search(raw):
                rec("raw-radius", "warning", path, i, "radius literal — use a token")
            d = duration.search(raw)
            if d and d.group(1) + d.group(2) not in ("0s", "0ms", "0.01ms"):
                rec("raw-duration", "warning", path, i, "duration literal — use a token")

for p in sys.argv[1:]:
    if not os.path.isfile(p): continue
    if re.search(r"(^|/)(node_modules|dist|build|coverage)/", p) or p.endswith(".min.css"): continue
    check(p)
PY
}

staged_css()  { git diff --cached --relative --name-only --diff-filter=ACMR -- '*.css' '*.scss' '*.svelte' '*.vue' 2>/dev/null; }
tracked_css() { git ls-files -- '*.css' '*.scss' '*.svelte' '*.vue' 2>/dev/null; }
